AWSTemplateFormatVersion: '2010-09-09'
Description: Assign IPv6 CIDRs to subnets using Lambda and a custom resource

Parameters:
  EnvironmentName:
    Type: String
  ProjectName:
    Type: String
  Department:
    Type: String
  CyberVpcId:
    Type: String
  TGWSubnetId1:
    Type: String
  TGWSubnetId2:
    Type: String
  ProxyNLBSubnetId1:
    Type: String
  ProxyNLBSubnetId2:
    Type: String
  ProxyPrivateSubnetId1:
    Type: String
  ProxyPrivateSubnetId2:
    Type: String
  MailRelayMgmtSubnetId1:
    Type: String
  MailRelayMgmtSubnetId2:
    Type: String
  MailRelayInternalSubnetId1:
    Type: String
  MailRelayInternalSubnetId2:
    Type: String
  MailRelayExternalSubnetId1:
    Type: String
  MailRelayExternalSubnetId2:
    Type: String
  LambdaCodeBucket:
    Type: String
  LambdaCodeKey:
    Type: String

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: AssignIpv6Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ec2:AssociateSubnetCidrBlock
            - ec2:DescribeVpcs
            - ec2:DescribeSubnets
            - ec2:AssociateVpcCidrBlock
            - ec2:DisassociateSubnetCidrBlock
            - ec2:DescribeVpcAttribute
            - ec2:ModifySubnetAttribute
            Resource: "*"
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"

  AssignIpv6Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: assign-ipv6-custom-resource
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs18.x
      Timeout: 60
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey

  AssignIpv6CustomResource:
    Type: Custom::AssignIpv6
    Properties:
      ServiceToken: !GetAtt AssignIpv6Function.Arn
      VpcId: !Ref CyberVpcId
      SubnetIds:
      - !Ref TGWSubnetId1
      - !Ref TGWSubnetId2
      - !Ref ProxyNLBSubnetId1
      - !Ref ProxyNLBSubnetId2
      - !Ref ProxyPrivateSubnetId1
      - !Ref ProxyPrivateSubnetId2
      - !Ref MailRelayMgmtSubnetId1
      - !Ref MailRelayMgmtSubnetId2
      - !Ref MailRelayInternalSubnetId1
      - !Ref MailRelayInternalSubnetId2
      - !Ref MailRelayExternalSubnetId1
      - !Ref MailRelayExternalSubnetId2
